AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.10

  Sample SAM Template for flickr-images-cherry-picker

Globals:
  Function:
    Timeout: 3

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-lambda
      Description: !Sub ${AWS::StackName}-lambda
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        LambdaFunctionEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./src/
      DockerTag: python3.10-v1

Outputs:
  LambdaFunctionEventApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
